** Flask Homework

*Name:* Jessica Novillo Argudo

*** Links
- Link to the Replit site: https://demo-flask-project.jessicanovillo.repl.co/
- Link to the Replit code: https://replit.com/@JessicaNovillo/Demo-Flask-Project

*** Notes homework Flask (part 2)

I created two forms: create_login and login.
I am implementing get and post methods separated to have a cleaner code and avoid mistakes:
- I implemented @app.get('/login') and @app.post('/login'). 
- I implemented @app.get('/create_login') and @app.post('/create_login'). 

If there are no users in the session, my code will ask to create an user and set up a password. Once credentials have been created, the user is redirected to the login form. Once logged in, the users can go to their account_page where they can add items to a "TODO list" which is going to be added to the session. Other users can also be created and have their own TODO list, which will be displayed if the log out and log in again.

There is a link in the account page that would Reset Session, this will remove all the accounts information.


*** Routes
- index (“/”)
- towers ("/towers")
- cleansing (“/cleansing”)
- tomebamba (“/tomebamba”)
- panama (“/panama”)
- turi (“/turi”)
- typical_food (“/typical_food”)
- international_food (“/international_food”)
- cajas (“/cajas”)
- chorro (“/chorro”)
- gualaceo (“/gualaceo”)
